### ISSUE TITLE
extraneous copies in bdlc::Queue

### ISSUE THREAD

**Issue by schmaltzlicker** [bloomberg/bde#194]
Hi, I'm just browsing your source and noticed what appear to be unnecessary copies in memShiftLeft and memShiftRight.

Elements are being copied from src to dest, then elements at src are destroyed. It seems that these should be move operations, or should be using your destructive move framework.

If my casual understanding of your code is incorrect then I apologize for the noise.

**Comment by RMGiroux** [comment]
Your understanding is correct, but I think that's what the "TBD efficiency" comments are referring to.

Would this be a performance bottleneck for your application?

**Comment by mversche** [comment]
`bdlc_queue` is deprecated in favor of `bsl::deque` btw.  It remains here

This might be the first deprecated component we've pushed to github (we left it in place because its still used in `bdlcc_queue`, which we haven't yet replaced).  

You can identify a deprecated component by the DEPRECATED section at the top of the documentation.  If you are browsing through the doxygen tree (http://bloomberg.github.io/bde/components.html), the component will be grayed out.

**Comment by mversche** [comment]
As the component is deprecated, I'm going to close this.

**Comment by schmaltzlicker** [comment]
I'm not a user of bde. I'm performing a survey of some C++ projects in order to provide additional justification for a proposal I am making. I happened upon this code during my search and it looked wrong so I put in a bug. :) I didn't notice that this class was deprecated. Apologies!

**Comment by RMGiroux** [comment]
No apologies needed - we appreciate the eyes on our code.  Don't hesitate to open other issues if you see something!
